### PR TITLE
Fix build error for valut-operator

### PR DESCRIPTION
**Pull request by nak3**
Fixes https://github.com/operator-framework/operator-sdk-samples/issues/46

Testing (`operator-sdk test `) still fails, but fixes for build first of all.

### CODE REVIEW

**Comment by estroz** [comment]
@nak3 thanks for opening a PR. There are a few other [migration steps](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md) that need to happen before vault-operator is up to date with the current SDK versions' expected file structure. You can implement migrations yourself if you have time, or one of the maintainers will do so in the near future.

**Comment by estroz** [comment]
@nak3 check out #48

**Comment by nak3** [comment]
@estroz Great! Thank you.

**Comment by camilamacedo86** [comment]
Closing this one as outdated since we decided to move forward just with the Memcached ones. 
However, please feel free to re-open if you think that would be required.

**Pull request closed without merging**
