### PR TITLE
Raise the Helm operator controller-manager memory limit to 200Mi.

### LINKED ISSUE #156: Helm sample operator default memory limit results in many OOMKilled restarts
I'm trying to deploy the sample operators to a variety of Kubernetes clusters, and it seems like of all the three, Helm seems to have trouble when deployed to both Kind and Minikube clusters locally.

The cluster has tons of free memory available, but the controller/manager pod keeps restarting. When I go to describe the pod, I see a lot of:

```
$ kubectl describe pod -n memcached-operator-system memcached-operator-controller-manager-6d57f5fd7-gfnxw
...
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Mon, 31 Aug 2020 16:32:42 -0500
      Finished:     Mon, 31 Aug 2020 16:33:08 -0500
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     100m
      memory:  90Mi
    Requests:
      cpu:        100m
      memory:     60Mi
```

And it only reconciles a one or zero CR instances before it's killed and restarts itself.

After raising the Deployment's `Limits.memory` to `256Mi`, it seemed to work fine with no restarts.

### PR DESCRIPTION
**Pull request by geerlingguy**
Fixes #156.﻿

### CODE REVIEW

**Comment by geerlingguy** [comment]
I can confirm that without this patch, if I deploy more than 3 or so Memcached CRs, the operator/controller gets stuck in an OOMKilled loop and slows down considerably.

With this patch I have tested up to 20 CRs and it's working without getting killed.

**Comment by camilamacedo86** [comment]
HI @geerlingguy, 

The samples are generated via script.  So, this change should be made on the script instead of it. However, we need to check better this issue. Note that the e2e tests are made with kind in the SDK repo. Did you check this issue just when you increase the amount of CR's? Could you please open an issue in the SDK repo and provide further information for we check if these values should be changed by default?

**Comment by geerlingguy** [comment]
> Did you check this issue just when you increase the amount of CR's?

Yes; with one CR I didn't run into any problems, it was only when I generated a number of CRs (in my case, 15 at first, and I kept backing off... sometimes 1, 2, or 3 would work with no `OOMKilled` statuses).

**Comment by camilamacedo86** [comment]
Hi @geerlingguy, 

OK. So, the sample is just to show how it works and will use 3 CR's by default which will no face issues. Also, according to your description in common cases, users will not face this issue since not necessary they will create a lot of CR's.  Then, I think we do not need to change the sample or the default values. However, shows that would be great document the issue and how to solve that. 

WDYT about pushing a PR against SDK doc repo? May add it in the FAQ since the memory issue and the solution as well shows a valid scenario for any type. I think that any project that will have many instances or work with many kinds might need to customize the limits.

**Comment by camilamacedo86** [comment]
hi @geerlingguy, 

Also, see that the idea is to deprecate this one. More info: https://github.com/operator-framework/operator-sdk-samples/pull/163.

So, I am closing this pr.

**Pull request closed without merging**
