### PR TITLE
WIP: Add multi-API memcached operator sample

### PR DESCRIPTION
**Pull request by simrandhaliw**

### CODE REVIEW

**Comment by simrandhaliw** [comment]
How can I generate CSV for this Operator? (It is based on this sample Operator: https://github.com/operator-framework/operator-sdk-samples/tree/master/go/kubebuilder/memcached-operator)

**Comment by camilamacedo86** [comment]
Hi @simrandhaliw, 

The appropriated way to get help s by raising an issue in the SDK repo. Could you please raise it? 
I am closing this PR since your goal is not to propose a change for this repo.

**Comment by simrandhaliw** [comment]
@camilamacedo86 

Sorry, I guess the question I asked in the comment might have suggested that I opened this PR to get that answered. But my main goal was to add this example operator as an example of conversion-webhook.

**Comment by varshaprasad96** [comment]
@simrandhaliw - Thanks for the PR, it is very helpful to have an example of this feature in SDK-samples. Ill be working on the conversion Webhook support along with OLM integration for SDK. I haven't looked into it much as of now, as we were currently working towards SDK 1.0 release. Will update as we progress and reach out to you. Meanwhile, please feel free to raise an issue with SDK if anything is required.

**Pull request closed without merging**
